### ISSUE TITLE
nbsmoke vs nbval vs jupyterlab_celltests

### ISSUE THREAD

**Issue by timkpaine** [pyviz-dev/nbsmoke#27]
AFAIK `nbval` can run top-to-bottom and ignore outputs with `py.test --nbval-lax`
And `jupyterlab_celltests` can run a linter (flake8 for now): https://github.com/timkpaine/jupyterlab_celltests/blob/master/jupyterlab_celltests/lint.py#L121

might be good to identify what these three projects overlap in and where they differ, and combine forces where possible. I've recently deleted all my code related to kernels and now rely on nbval for that bit. 

xref https://github.com/timkpaine/jupyterlab_celltests/issues/1

**Comment by ceball** [comment]
I think that's a great idea - thanks for opening this issue. We always wanted to integrate with nbval (and originally with nbsite, too.) I'm pretty sure nbsmoke was supposed to be temporary when it started ;) I'm not familiar with jupyterlab_celltests, but it looks very interesting and I'd like to learn about it.

What about we make a feature matrix to start off with, comparing the three? Or any better idea of a good way to start? I definitely think it's worthwhile doing a comparison in some form.

**Comment by ceball** [comment]
Since I'm here, I'll just quickly try to summarize where nbsmoke is currently. In order of speed to run (at least in theory!), nbsmoke supports:
  * "linting" notebooks: a notebook is converted to python (using nbconvert), then it is checked using pyflakes. I.e. fast, catching obviously bad things (undefined names, unused imports, etc) - the minimal things, with no false positives, so that running these tests might one day be accepted by sceptical notebook authors ;)
  * "verifying" notebooks: I can't remember what exactly this includes, but it's things like: are links, images, etc valid? are all imported modules installed? I.e. further checks, but still short of running the notebook. This functionality was copied in from bokeh's tests some time ago, but I can't remember if we use it yet. Maybe just in datashader at the moment, or something like that.
* "running" notebooks: executing from top to bottom, failing on exception.

I doubt nbsmoke has anything over any other tool for the 'run tests'. The 'verify tests' might be unique, but we haven't used them much. The 'lint tests' have support for magics, which might be different from other tools (not sure!):
  * Magics that obviously interact with the python process can be handled. E.g. `%time x = fn()` will be checked as `x = fn()`, `%%capture x` will result in `x` being defined. `%%script bash` will be ignored, but `%%script bash --out=x` will result in `x` being defined. Not sure if this magics handling is a good idea or not (I tend not to use magics). This magics handling is extensible.
  * Magics that don't obviously interact with the python process are skipped.
  * Supports a 'magics blacklist' (so you can ban whatever magics you think are a bad idea!).

Though the lint testing only uses pyflakes (not flake8), it supports ignoring of flakes (by regex or adding `# noqa: explanation`). So a bit like flake8, but not as sophisticated - more as a proof of concept. It can also emit only warnings rather than failures if preferred.

(Note that some of the above isn't in the current nbsmoke release, but will be in the next one, which is coming soon.)
